// Generated by CoffeeScript 1.12.5
var CowText, ShowEdit, display, makeUrlPart, parseUrl, updateCows;

CowText = '@*! I say moo! You say party! @>\n@! Moo!                       @> Party!\n@! Moo!                       @> Party!';

ShowEdit = true;

$(document).ready(function() {
  $('#cowsay-submit').click(updateCows);
  parseUrl();
  return display();
});

parseUrl = function() {
  var param;
  param = window.location.hash;
  console.log("param=[" + param + "]");
  if (!param.match(/^#(view|edit)\..+/)) {
    return false;
  }
  ShowEdit = param.substr(1, 4) === 'edit';
  CowText = LZString.decompressFromBase64(param.substr(6));
  return true;
};

makeUrlPart = function(action, text) {
  return '#' + action + '.' + LZString.compressToBase64(text);
};

display = function() {
  var r, rtext;
  r = new CowSay;
  rtext = r.render(CowText);
  $('#ascii_art').get(0).textContent = rtext;
  $('#cowsay-input-form').attr('hidden', !ShowEdit);
  $('#cowsay-text').val(CowText);
  $('#cow-dlg-link').attr('href', makeUrlPart('view', CowText));
  return $('#cow-dlg-link-edit').attr('href', makeUrlPart('edit', CowText));
};

updateCows = function() {
  CowText = $("#cowsay-text").val();
  return display();
};
